# Arquivo: .github/workflows/deploy.yml

name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # Executa o workflow somente na branch main

jobs:
  deploy:
    name: Deploy to FTP Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Faz o checkout do código

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # Diretório local a ser enviado
        server-dir: /htdocs  # Diretório remoto no servidor
